### PR TITLE
Print out array keys

### PR DESCRIPTION
**Pull request by convenient**
Print out array keys.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thinking about it, it might make sense to always show the keys.

**Comment by convenient** [comment]
Sure, I can make this refactor.

**Comment by convenient** [comment]
@sebastianbergmann Refactored and tests passing.

**Comment by convenient** [comment]
I'm not sure whether the failed test here is legitimate.

```
Runtime:       PHP 7.2.0-dev with Xdebug 2.6.0-dev
Configuration: /home/travis/build/sebastianbergmann/object-graph/phpunit.xml
/home/travis/.travis/job_stages: line 57:  2770 Segmentation fault      (core dumped) ./vendor/bin/phpunit --coverage-clover=coverage.xml
```

It's working for me locally as well as in PHP 7.1.

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it. Instead I implemented the functionality differently in 1282d65ff4d8d8627feff07d626f83a600e0bd16.

**Pull request closed without merging**
